from __future__ import annotations

from collections.abc import Callable
from typing import Literal, TypeAlias


AgentStatus: TypeAlias = Literal[
    "thinking",
    "listing files",
    "listing tree",
    "mapping repo",
    "reading file",
    "reading files",
    "reading file ranges",
    "reading file info",
    "reading python symbols",
    "reading code outline",
    "checking python",
    "checking config",
    "checking json set",
    "setting json",
    "checking json remove",
    "removing json",
    "checking json patch",
    "patching json",
    "reading python dependencies",
    "reading python definitions",
    "reading python calls",
    "reading python call graph",
    "reading python references",
    "previewing python rename",
    "renaming python symbol",
    "searching",
    "globbing",
    "checking git status",
    "reading git branches",
    "checking git fetch",
    "fetching git remote",
    "checking git pull",
    "pulling git upstream",
    "checking git push",
    "pushing git upstream",
    "checking git restore",
    "restoring git paths",
    "reading git stashes",
    "checking git stash",
    "stashing git changes",
    "checking git stash apply",
    "applying git stash",
    "checking git stash drop",
    "dropping git stash",
    "checking git switch",
    "switching git branch",
    "reading git changes",
    "reviewing changes",
    "final reviewing changes",
    "suggesting checks",
    "reading project overview",
    "checking command",
    "checking commands",
    "checking http",
    "reading environment info",
    "reading git diff",
    "reading git log",
    "reading git show",
    "reading git blame",
    "reading session summary",
    "editing file",
    "multi-editing file",
    "replacing python definition",
    "replacing lines",
    "inserting lines",
    "checking patch",
    "checking patches",
    "patching file",
    "patching files",
    "deleting file",
    "checking file deletes",
    "deleting files",
    "moving file",
    "checking file moves",
    "moving files",
    "checking file copies",
    "copying files",
    "checking directory moves",
    "moving directories",
    "checking directory copies",
    "copying directories",
    "checking directory creates",
    "creating directories",
    "checking empty directory deletes",
    "deleting empty directories",
    "writing file",
    "writing files",
    "running command",
    "running commands",
    "starting command",
    "reading process",
    "waiting process",
    "checking process write",
    "writing process",
    "listing processes",
    "stopping process",
    "updating plan",
    "step started",
    "step completed",
    "approval required",
    "approval approved",
    "approval denied",
    "observed success",
    "observed failure",
    "finished",
]

# Logger receives a status plus optional detail for each agent transition.
AgentLogger: TypeAlias = Callable[[AgentStatus, str | None], None]
