from __future__ import annotations


DIRECT_FAILURE_KINDS = {
    "tool_error",
    "approval_denied",
}

OK_FLAG_FAILURE_KINDS = {
    "memory_list",
    "memory_read",
    "check_memory_write",
    "memory_write",
    "enter_worktree",
    "exit_worktree",
    "delegate_task",
    "task_output",
    "task_stop",
    "task_create",
    "task_get",
    "task_list",
    "task_update",
    "check_write_file",
    "write_file",
    "check_write_files",
    "write_files",
    "checkpoint_create",
    "check_edit_file",
    "edit_file",
    "check_multi_edit_file",
    "multi_edit_file",
    "notebook_read",
    "check_notebook_edit",
    "notebook_edit",
    "check_replace_python_definition",
    "replace_python_definition",
    "check_replace_lines",
    "replace_lines",
    "check_insert_lines",
    "insert_lines",
    "check_append_file",
    "append_file",
    "regex_replace",
    "check_regex_replace",
    "check_json_set",
    "json_set",
    "check_json_remove",
    "json_remove",
    "check_json_patch",
    "json_patch",
    "check_patch",
    "check_patches",
    "patch_file",
    "patch_files",
    "check_delete_file",
    "delete_file",
    "check_delete_files",
    "delete_files",
    "check_move_file",
    "move_file",
    "check_move_files",
    "move_files",
    "check_copy_file",
    "copy_file",
    "check_copy_files",
    "copy_files",
    "check_move_dir",
    "move_dir",
    "check_move_dirs",
    "move_dirs",
    "check_copy_dir",
    "copy_dir",
    "check_copy_dirs",
    "copy_dirs",
    "check_create_dir",
    "create_dir",
    "check_create_dirs",
    "create_dirs",
    "check_delete_empty_dir",
    "delete_empty_dir",
    "check_delete_empty_dirs",
    "delete_empty_dirs",
    "check_set_executable",
    "set_executable",
    "run_commands",
    "run_focused_test_commands",
    "port_check",
    "http_check",
    "http_fetch",
    "web_fetch",
    "web_search",
    "start_command",
    "read_process",
    "wait_process",
    "check_write_process",
    "write_process",
    "check_stop_all_processes",
    "check_stop_process",
    "stop_all_processes",
    "stop_process",
    "repo_map",
    "read_file_context",
    "tail_file",
    "view_image",
    "python_check",
    "config_check",
    "python_dependencies",
    "code_dependencies",
    "code_references",
    "code_reference_contexts",
    "code_definitions",
    "code_rename_preview",
    "code_rename",
    "python_definitions",
    "python_calls",
    "python_call_graph",
    "python_references",
    "python_reference_contexts",
    "python_rename_preview",
    "python_rename",
    "search",
    "search_contexts",
    "find_files",
    "glob",
    "list_tree",
    "git_status",
    "git_conflicts",
    "git_diff_contexts",
    "git_info",
    "git_changes",
    "git_branches",
    "check_git_fetch",
    "git_fetch",
    "check_git_pull",
    "git_pull",
    "check_git_push",
    "git_push",
    "check_git_restore",
    "git_restore",
    "git_stashes",
    "check_git_stash",
    "git_stash",
    "check_git_stash_apply",
    "git_stash_apply",
    "check_git_stash_drop",
    "git_stash_drop",
    "check_git_switch",
    "git_switch",
    "check_git_stage",
    "git_stage",
    "check_git_unstage",
    "git_unstage",
    "check_git_commit",
    "git_commit",
    "review_changes",
    "final_review",
    "suggest_checks",
    "check_suggested_checks",
    "run_suggested_checks",
    "project_commands",
    "tool_search",
    "related_tests",
    "focused_test_commands",
    "check_focused_test_commands",
    "project_manifests",
    "project_instructions",
    "project_skills",
    "project_agents",
    "skill",
    "mcp_servers",
    "mcp_tools",
    "mcp_call",
    "project_todos",
    "project_overview",
    "command_check",
    "check_run_commands",
    "check_start_command",
    "environment_info",
    "git_diff",
    "git_diff_hunks",
    "git_log",
    "git_show",
    "git_blame",
    "session_summary",
    "session_plan",
    "session_transcript",
    "session_search",
    "session_commands",
    "session_output_contexts",
    "session_output_diagnostics",
    "process_output_contexts",
    "process_output_diagnostics",
    "session_files",
    "session_failures",
    "session_verification",
    "run_session_verification",
    "session_audit",
    "session_handoff",
    "checkpoint_list",
    "checkpoint_show",
    "checkpoint_diff",
    "checkpoint_status",
    "check_checkpoint_restore",
    "checkpoint_restore",
    "check_checkpoint_delete",
    "checkpoint_delete",
    "check_checkpoint_prune",
    "checkpoint_prune",
}

ITEM_OK_FAILURE_COLLECTIONS = {
    "read_file_contexts": "contexts",
    "output_contexts": "contexts",
    "output_diagnostics": "contexts",
    "read_files": "files",
    "read_file_ranges": "ranges",
    "file_info": "files",
    "image_info": "images",
    "python_symbols": "files",
    "code_outline": "files",
}

NON_FAILURE_KINDS = {
    "list_processes",
    "update_plan",
}

MESSAGE_PREFIX_SUCCESS_KINDS = {
    "read_file": ("Read ",),
    "list_files": ("Found ", "Already listed "),
}


def ok_observation_failure_kinds() -> set[str]:
    return OK_FLAG_FAILURE_KINDS | set(ITEM_OK_FAILURE_COLLECTIONS) | set(MESSAGE_PREFIX_SUCCESS_KINDS)
