from __future__ import annotations


AGENT_HOOK_ALLOWED_TOOL_NAMES = frozenset(
    {
        "Glob",
        "Grep",
        "LS",
        "NotebookRead",
        "Read",
        "TodoRead",
        "code_definitions",
        "code_dependencies",
        "code_outline",
        "code_reference_contexts",
        "code_references",
        "code_rename_preview",
        "config_check",
        "file_info",
        "find_files",
        "finish",
        "focused_test_commands",
        "git_blame",
        "git_branches",
        "git_changes",
        "git_conflicts",
        "git_diff",
        "git_diff_contexts",
        "git_diff_hunks",
        "git_info",
        "git_log",
        "git_show",
        "git_stashes",
        "git_status",
        "glob",
        "image_info",
        "list_files",
        "list_tree",
        "project_commands",
        "project_instructions",
        "project_manifests",
        "project_overview",
        "project_skills",
        "python_call_graph",
        "python_calls",
        "python_check",
        "python_definitions",
        "python_dependencies",
        "python_reference_contexts",
        "python_references",
        "python_rename_preview",
        "python_symbols",
        "read_file",
        "read_file_context",
        "read_file_contexts",
        "read_file_ranges",
        "read_files",
        "related_tests",
        "repo_map",
        "review_changes",
        "search",
        "search_contexts",
        "suggest_checks",
        "tail_file",
    }
)


__all__ = ["AGENT_HOOK_ALLOWED_TOOL_NAMES"]
