from __future__ import annotations

import argparse
from collections.abc import Sequence
import os
from pathlib import Path

from .agent import run_agent
from .chat import run_chat
from .cli_exit_codes import (
    LOCAL_RESULT_ARG_NAMES,
    has_bad_session_summary_status,
    has_incomplete_top_level_count,
    has_local_diagnostic_error,
    has_positive_top_level_count,
    has_process_status_failure,
    has_session_verification_issue,
    has_top_level_error,
    has_top_level_field,
    has_top_level_ok,
    local_result_arg_selected,
    process_status_value_failed,
)
from .cli_args import has_local_flag, parse_args
from .cli_config import (
    build_provider_env,
    format_save_config_report_text,
    resolve_project_root,
    save_project_config_from_args,
    save_project_config_report_from_args,
)
from .cli_output import (
    build_approval_handler,
    format_error,
    handle_approval_command,
    print_agent_result,
    print_error_result,
    print_interrupted_result,
    prompt_approval,
)
from .cli_checkpoint_local_flags import run_checkpoint_local_flag
from .cli_code_intel_local_flags import run_code_intel_local_flag, run_python_local_flag
from .cli_command_local_flags import run_command_local_flag
from .cli_edit_local_flags import run_edit_local_flag
from .cli_local_result import emit_local_result
from .cli_git_local_flags import run_git_local_flag
from .cli_json_local_flags import run_json_local_flag
from .cli_local_dispatch import dispatch_local_flag
from .cli_patch_local_flags import run_patch_local_flag
from .cli_session_local_flags import run_session_local_flag
from .cli_interactive import run_interactive_loop as _run_interactive_loop
from .cli_main_args import normalize_task_bound_diff_args
from .cli_runner import (
    build_one_shot_kwargs_from_args,
    resolve_task_text,
    run_one_shot as _run_one_shot,
)
from .cli_review_local_flags import run_review_local_flag
from .cli_read_local_flags import run_read_local_flag
from .cli_project_local_flags import run_project_local_flag
from .cli_session_kwargs import (
    session_audit_kwargs,
    session_commands_kwargs,
    session_failures_kwargs,
    session_files_kwargs,
    session_handoff_kwargs,
    session_output_contexts_kwargs,
    session_output_diagnostics_kwargs,
    run_session_verification_kwargs,
    session_search_kwargs,
    session_transcript_kwargs,
    session_verification_kwargs,
)
from .cli_runtime_local_flags import run_runtime_local_flag
from .cli_text_edit_local_flags import run_text_edit_local_flag
from .cli_validation import validate_cli_args
from .cli_parse_core import build_focused_tests_kwargs
from .cli_parse_diff_git import (
    build_stash_argument,
    build_switch_argument,
    parse_interactive_diff_argument,
    parse_interactive_diff_contexts_argument,
    parse_interactive_diff_hunks_argument,
)
from .cli_parse_session import (
    parse_interactive_session_detail_argument,
    parse_interactive_run_session_verification_argument,
    parse_interactive_session_search_argument,
    parse_interactive_transcript_argument,
)
from .cli_parse_runtime_checks import (
    parse_interactive_http_argument,
    parse_interactive_http_fetch_argument,
    parse_interactive_port_argument,
    parse_interactive_process_output_argument,
)
from .cli_parse_discovery import (
    parse_interactive_commands_argument,
    parse_interactive_find_files_argument,
    parse_interactive_glob_argument,
    parse_interactive_instructions_argument,
    parse_interactive_manifests_argument,
    parse_interactive_option_limit_argument,
    parse_interactive_overview_argument,
    parse_interactive_repo_map_argument,
    parse_interactive_search_argument,
    parse_interactive_todos_argument,
)
from .cli_parse_read import (
    parse_interactive_around_argument,
    parse_interactive_around_many_argument,
    parse_interactive_max_bytes_argument,
    parse_interactive_output_analysis_argument,
    parse_interactive_read_argument,
    parse_interactive_read_files_argument,
    parse_interactive_read_ranges_argument,
    parse_interactive_symbols_argument,
    parse_interactive_tail_argument,
    parse_interactive_tree_argument,
)
from .cli_parse_code_intel import (
    parse_interactive_python_call_graph_argument,
    parse_interactive_python_deps_argument,
    parse_interactive_python_symbol_argument,
    parse_interactive_test_paths_argument,
)
from .cli_parse_run import (
    parse_interactive_check_run_sequence_argument,
    parse_interactive_cwd_command_argument,
    parse_interactive_run_argument,
    parse_interactive_run_focused_tests_argument,
    parse_interactive_run_sequence_argument,
    parse_interactive_run_suggested_checks_argument,
    parse_interactive_wait_process_argument,
)
from .commands import (
    get_append_file_report,
    get_append_file_text,
    get_help_text,
    format_blame_report_text,
    format_branches_report_text,
    format_git_commit_report_text,
    format_git_fetch_report_text,
    format_git_info_report_text,
    format_git_pull_report_text,
    format_git_push_report_text,
    format_git_restore_report_text,
    format_git_stash_apply_report_text,
    format_git_stash_drop_report_text,
    format_git_stash_report_text,
    format_git_status_report_text,
    format_git_switch_report_text,
    format_git_sync_preview_report_text,
    format_find_files_report_text,
    format_glob_report_text,
    format_file_info_report_text,
    format_image_info_report_text,
    format_json_patch_report_text,
    format_json_pointer_report_text,
    format_log_report_text,
    format_around_report_text,
    format_around_many_report_text,
    format_output_contexts_report_text,
    format_output_diagnostics_report_text,
    format_process_report_text,
    format_process_output_contexts_report_text,
    format_process_output_diagnostics_report_text,
    format_python_traceback_report_text,
    format_regex_replace_report_text,
    format_executable_report_text,
    format_permissions_report_text,
    format_patch_report_text,
    format_patches_report_text,
    format_path_action_report_text,
    format_path_list_report_text,
    format_file_transfer_list_report_text,
    format_file_transfer_report_text,
    format_read_report_text,
    format_read_files_report_text,
    format_read_ranges_report_text,
    format_show_report_text,
    format_stashes_report_text,
    format_symbols_report_text,
    format_tree_report_text,
    format_session_transcript_report_text,
    get_blame_report,
    get_blame_text,
    get_branches_report,
    get_branches_text,
    get_compact_context,
    get_checks_report,
    get_checks_text,
    format_changes_report_text,
    get_changes_report,
    get_changes_text,
    format_check_checkpoint_delete_report_text,
    format_check_checkpoint_prune_report_text,
    format_checkpoint_create_report_text,
    format_checkpoint_delete_report_text,
    format_checkpoint_diff_report_text,
    format_checkpoint_prune_report_text,
    format_check_checkpoint_restore_report_text,
    format_checkpoint_restore_report_text,
    format_checkpoint_show_report_text,
    format_checkpoint_status_report_text,
    format_checkpoints_report_text,
    get_check_checkpoint_delete_text,
    get_check_checkpoint_delete_report,
    get_check_checkpoint_prune_text,
    get_check_checkpoint_prune_report,
    get_check_checkpoint_restore_text,
    get_check_checkpoint_restore_report,
    get_checkpoint_diff_report,
    get_checkpoint_diff_text,
    get_checkpoint_delete_report,
    get_checkpoint_delete_text,
    get_checkpoint_prune_report,
    get_checkpoint_prune_text,
    get_checkpoint_restore_report,
    get_checkpoint_restore_text,
    get_checkpoint_report,
    get_checkpoint_show_report,
    get_checkpoint_show_text,
    get_checkpoint_status_report,
    get_checkpoint_status_text,
    get_checkpoint_text,
    get_checkpoints_report,
    get_checkpoints_text,
    get_check_copy_dir_text,
    get_check_copy_dir_report,
    get_check_copy_dirs_text,
    get_check_copy_dirs_report,
    get_check_copy_file_report,
    get_check_copy_file_text,
    get_check_copy_files_report,
    get_check_copy_files_text,
    get_check_create_dirs_text,
    get_check_create_dirs_report,
    get_check_create_dir_text,
    get_check_create_dir_report,
    get_check_delete_file_report,
    get_check_delete_file_text,
    get_check_delete_files_report,
    get_check_delete_files_text,
    get_check_delete_empty_dirs_text,
    get_check_delete_empty_dirs_report,
    get_check_delete_empty_dir_text,
    get_check_delete_empty_dir_report,
    get_check_edit_file_report,
    get_check_edit_file_text,
    get_check_fetch_report,
    get_check_fetch_text,
    get_check_pull_report,
    get_check_pull_text,
    get_check_push_report,
    get_check_push_text,
    get_check_set_executable_text,
    get_check_set_executable_report,
    get_check_stash_report,
    get_check_stash_text,
    get_check_stash_apply_report,
    get_check_stash_apply_text,
    get_check_stash_drop_report,
    get_check_stash_drop_text,
    get_check_switch_report,
    get_check_switch_text,
    get_check_append_file_report,
    get_check_append_file_text,
    get_check_insert_lines_report,
    get_check_insert_lines_text,
    get_check_move_dir_text,
    get_check_move_dir_report,
    get_check_move_dirs_text,
    get_check_move_dirs_report,
    get_check_move_file_report,
    get_check_move_file_text,
    get_check_move_files_report,
    get_check_move_files_text,
    get_check_multi_edit_file_report,
    get_check_multi_edit_file_text,
    get_check_patch_text,
    get_check_patch_report,
    get_check_patches_text,
    get_check_patches_report,
    get_check_write_file_report,
    get_check_write_file_text,
    get_check_write_files_report,
    get_check_write_files_text,
    format_write_files_report_text,
    format_check_run_sequence_report_text,
    get_check_run_sequence_report,
    get_check_run_sequence_text,
    format_check_start_report_text,
    get_check_start_report,
    get_check_start_text,
    get_check_stop_all_processes_text,
    format_check_stop_all_processes_report_text,
    get_check_stop_all_processes_report,
    format_check_stop_process_report_text,
    get_check_stop_process_report,
    get_check_stop_process_text,
    get_check_commit_report,
    get_check_commit_text,
    get_check_json_patch_text,
    get_check_json_patch_report,
    get_check_regex_replace_text,
    get_check_regex_replace_report,
    get_check_replace_lines_report,
    get_check_replace_lines_text,
    get_check_replace_python_definition_report,
    get_check_replace_python_definition_text,
    format_line_edit_report_text,
    format_replace_python_definition_report_text,
    get_check_restore_report,
    get_check_restore_text,
    format_git_index_report_text,
    get_check_stage_report,
    get_check_unstage_report,
    get_check_stage_text,
    get_check_unstage_text,
    get_check_json_remove_text,
    get_check_json_remove_report,
    get_check_json_set_text,
    get_check_json_set_report,
    format_code_defs_report_text,
    format_code_deps_report_text,
    format_code_ref_contexts_report_text,
    format_code_refs_report_text,
    format_code_rename_report_text,
    get_code_defs_report,
    get_code_defs_text,
    get_code_deps_report,
    get_code_deps_text,
    get_code_ref_contexts_report,
    get_code_ref_contexts_text,
    get_code_rename_preview_report,
    get_code_rename_preview_text,
    get_code_rename_report,
    get_code_rename_text,
    get_code_refs_report,
    get_code_refs_text,
    format_command_check_report_text,
    get_command_check_report,
    get_command_check_text,
    get_commands_text,
    format_checks_report_text,
    format_config_check_report_text,
    get_config_check_report,
    format_config_report_text,
    get_config_report,
    get_config_text,
    format_context_report_text,
    get_context_report,
    get_context_text,
    format_env_report_text,
    get_commit_text,
    get_commit_report,
    get_config_check_text,
    get_copy_dir_text,
    get_copy_dir_report,
    get_copy_dirs_text,
    get_copy_dirs_report,
    get_copy_file_report,
    get_copy_file_text,
    get_copy_files_report,
    get_copy_files_text,
    get_cost_report,
    format_cost_report_text,
    get_cost_text,
    get_create_dirs_text,
    get_create_dirs_report,
    get_create_dir_text,
    get_create_dir_report,
    get_delete_file_report,
    get_delete_file_text,
    get_delete_files_report,
    get_delete_files_text,
    get_delete_empty_dirs_text,
    get_delete_empty_dirs_report,
    get_delete_empty_dir_text,
    get_delete_empty_dir_report,
    format_diff_contexts_report_text,
    format_diff_hunks_report_text,
    format_diff_report_text,
    get_diff_contexts_report,
    get_diff_hunks_text,
    get_diff_hunks_report,
    get_diff_contexts_text,
    get_diff_report,
    get_diff_text,
    get_doctor_report,
    format_doctor_report_text,
    get_doctor_text,
    get_edit_file_report,
    get_edit_file_text,
    get_env_report,
    get_env_text,
    get_fetch_text,
    get_fetch_report,
    get_file_info_report,
    get_file_info_text,
    get_image_info_report,
    get_image_info_text,
    format_git_conflicts_report_text,
    get_git_conflicts_report,
    get_git_info_text,
    get_git_info_report,
    get_git_conflicts_text,
    get_git_status_report,
    get_git_status_text,
    get_find_files_report,
    get_find_files_text,
    get_glob_report,
    get_glob_text,
    format_handoff_report_text,
    get_handoff_report,
    get_handoff_text,
    format_http_fetch_report_text,
    get_http_fetch_report,
    get_http_fetch_text,
    format_http_report_text,
    get_http_report,
    get_http_text,
    get_insert_lines_report,
    get_insert_lines_text,
    format_instructions_report_text,
    get_instructions_report,
    get_instructions_text,
    format_init_report_text,
    get_init_report,
    get_json_patch_text,
    get_json_patch_report,
    get_json_remove_text,
    get_json_remove_report,
    get_json_set_text,
    get_json_set_report,
    get_last_session_report,
    get_last_session_text,
    get_log_report,
    get_log_text,
    format_manifests_report_text,
    get_manifests_report,
    get_manifests_text,
    format_model_report_text,
    get_model_report,
    get_model_text,
    get_move_dir_text,
    get_move_dir_report,
    get_move_dirs_text,
    get_move_dirs_report,
    get_move_file_report,
    get_move_file_text,
    get_move_files_report,
    get_move_files_text,
    get_multi_edit_file_report,
    get_multi_edit_file_text,
    format_overview_report_text,
    get_overview_report,
    get_overview_text,
    get_patch_text,
    get_patch_report,
    get_patches_text,
    get_patches_report,
    get_permissions_report,
    get_permissions_text,
    get_plan_report,
    get_plan_text,
    format_port_report_text,
    get_port_report,
    get_port_text,
    get_pull_text,
    get_pull_report,
    get_push_text,
    get_push_report,
    format_commands_report_text,
    get_commands_report,
    format_check_suggested_checks_report_text,
    get_check_suggested_checks_report,
    get_check_suggested_checks_text,
    get_around_report,
    get_around_many_report,
    get_around_text,
    get_around_many_text,
    get_output_contexts_report,
    get_output_contexts_text,
    get_output_diagnostics_report,
    get_output_diagnostics_text,
    get_process_output_contexts_report,
    get_process_output_contexts_text,
    get_process_output_diagnostics_report,
    get_process_output_diagnostics_text,
    get_process_report,
    get_process_text,
    format_processes_report_text,
    get_processes_report,
    get_processes_text,
    format_check_write_process_report_text,
    get_check_write_process_report,
    get_check_write_process_text,
    get_python_traceback_text,
    get_python_traceback_report,
    format_python_call_graph_report_text,
    get_python_call_graph_report,
    get_python_call_graph_text,
    format_python_calls_report_text,
    get_python_calls_report,
    get_python_calls_text,
    format_python_check_report_text,
    get_python_check_report,
    get_python_check_text,
    format_python_defs_report_text,
    get_python_defs_report,
    get_python_defs_text,
    format_python_deps_report_text,
    get_python_deps_report,
    get_python_deps_text,
    format_python_ref_contexts_report_text,
    get_python_ref_contexts_report,
    get_python_ref_contexts_text,
    format_python_refs_report_text,
    get_python_refs_report,
    get_python_refs_text,
    format_python_rename_report_text,
    get_python_rename_preview_report,
    get_python_rename_preview_text,
    get_python_rename_report,
    get_python_rename_text,
    get_read_report,
    get_read_files_report,
    get_read_ranges_report,
    get_read_files_text,
    get_read_ranges_text,
    get_read_text,
    get_regex_replace_text,
    get_regex_replace_report,
    format_check_focused_test_commands_report_text,
    get_check_focused_test_commands_report,
    get_check_focused_test_commands_text,
    format_focused_test_commands_report_text,
    get_focused_test_commands_report,
    get_focused_test_commands_text,
    format_related_tests_report_text,
    get_related_tests_report,
    get_related_tests_text,
    format_run_focused_test_commands_report_text,
    get_run_focused_test_commands_report,
    get_run_focused_test_commands_text,
    get_replace_lines_report,
    get_replace_lines_text,
    get_replace_python_definition_report,
    get_replace_python_definition_text,
    get_restore_report,
    format_repo_map_report_text,
    get_repo_map_report,
    get_repo_map_text,
    format_review_report_text,
    get_review_report,
    get_review_text,
    get_resume_context,
    get_restore_text,
    format_run_report_text,
    get_run_report,
    format_run_session_verification_report_text,
    get_run_session_verification_report,
    get_run_session_verification_text,
    format_run_sequence_report_text,
    get_run_sequence_report,
    get_run_sequence_text,
    format_run_suggested_checks_report_text,
    get_run_suggested_checks_report,
    get_run_suggested_checks_text,
    get_run_text,
    get_session_audit_report,
    format_session_audit_report_text,
    get_session_audit_text,
    get_session_commands_report,
    format_session_commands_report_text,
    get_session_commands_text,
    get_session_output_contexts_report,
    format_session_output_contexts_report_text,
    get_session_output_contexts_text,
    get_session_output_diagnostics_report,
    format_session_output_diagnostics_report_text,
    get_session_output_diagnostics_text,
    get_session_failures_report,
    format_session_failures_report_text,
    get_session_failures_text,
    get_session_files_report,
    format_session_files_report_text,
    get_session_files_text,
    get_session_handoff_report,
    format_session_handoff_report_text,
    get_session_handoff_text,
    get_session_report,
    format_session_plan_report_text,
    format_session_search_report_text,
    format_session_summary_report_text,
    format_session_verification_report_text,
    get_session_search_report,
    get_session_text,
    get_session_verification_report,
    get_session_verification_text,
    get_sessions_report,
    format_sessions_report_text,
    get_sessions_text,
    format_search_contexts_report_text,
    format_search_report_text,
    get_search_report,
    get_search_text,
    get_search_contexts_report,
    get_search_contexts_text,
    get_session_search_text,
    get_set_executable_text,
    get_set_executable_report,
    get_show_report,
    get_show_text,
    format_start_report_text,
    get_start_report,
    get_start_text,
    get_stash_apply_report,
    get_stash_apply_text,
    get_stash_drop_report,
    get_stash_drop_text,
    get_stash_report,
    get_stash_text,
    get_stage_report,
    get_stage_text,
    get_stashes_text,
    get_stashes_report,
    format_status_report_text,
    get_status_report,
    get_status_text,
    get_tail_report,
    get_tail_text,
    format_tail_report_text,
    format_todos_report_text,
    get_todos_report,
    get_todos_text,
    get_stop_all_processes_text,
    format_stop_all_processes_report_text,
    get_stop_all_processes_report,
    format_stop_process_report_text,
    get_stop_process_report,
    get_stop_process_text,
    get_switch_text,
    get_switch_report,
    get_symbols_report,
    get_symbols_text,
    format_tool_report_text,
    get_tool_report,
    get_tool_text,
    format_tools_report_text,
    get_tools_report,
    get_tools_text,
    get_tree_report,
    get_tree_text,
    get_transcript_report,
    get_transcript_text,
    get_unstage_text,
    get_unstage_report,
    get_usage_report,
    format_usage_report_text,
    get_usage_text,
    get_wait_process_text,
    get_wait_process_report,
    format_wait_process_report_text,
    get_write_file_report,
    get_write_file_text,
    get_write_files_report,
    get_write_files_text,
    format_write_process_report_text,
    get_write_process_report,
    get_write_process_text,
    init_project_instructions,
    parse_local_command,
)
from .providers import create_chat_client


def main(argv: Sequence[str] | None = None) -> int:
    if argv is not None:
        args = parse_args(argv)
        validation_error = validate_cli_args(args)
        if validation_error is not None:
            return print_error_result(validation_error, args.json, exit_code=2)
        normalize_task_bound_diff_args(args)
        if has_local_flag(args):
            if args.task:
                return print_error_result("Local command flags cannot be combined with a task.", args.json, exit_code=2)
            return run_local_flag(args)
        if args.task:
            return run_one_shot(**build_one_shot_kwargs_from_args(args))
    if argv is not None:
        try:
            return run_interactive(args.cwd)
        except KeyboardInterrupt:
            return print_interrupted_result(args.json)
        except ValueError as error:
            return print_error_result(str(error), args.json, exit_code=2)
    return run_interactive()




def run_local_flag(args: argparse.Namespace) -> int:
    try:
        project_root = resolve_project_root(args.cwd)
        config_root = project_root or Path.cwd()
        payload_extra: dict[str, object] = {}
        if args.save_config:
            if args.json:
                save_config_report = save_project_config_report_from_args(args, config_root)
                payload_extra["saveConfig"] = save_config_report
                text = format_save_config_report_text(save_config_report)
            else:
                text = save_project_config_from_args(args, config_root)
        else:
            provider_env = build_provider_env(args, config_root)
            if (flag_result := dispatch_local_flag(args, project_root, config_root, provider_env, globals())) is not None:
                text, payload = flag_result
                payload_extra.update(payload)
            else:
                text = ""
        return emit_local_result(args, text, payload_extra)
    except KeyboardInterrupt:
        return print_interrupted_result(args.json)
    except Exception as error:
        return print_error_result(format_error(error), args.json, prefix=True)


def run_interactive(base_dir: str | None = None) -> int:
    project_root = resolve_project_root(base_dir)
    if project_root is None:
        return run_interactive_loop()

    previous_cwd = Path.cwd()
    os.chdir(project_root)
    try:
        return run_interactive_loop()
    finally:
        os.chdir(previous_cwd)


def run_one_shot(*args, **kwargs) -> int:
    kwargs.setdefault("create_chat_client_func", create_chat_client)
    kwargs.setdefault("run_chat_func", run_chat)
    kwargs.setdefault("run_agent_func", run_agent)
    kwargs.setdefault("get_resume_context_func", get_resume_context)
    kwargs.setdefault("get_compact_context_func", get_compact_context)
    return _run_one_shot(*args, **kwargs)


def run_interactive_loop() -> int:
    return _run_interactive_loop(
        command_namespace=globals(),
        create_chat_client_func=create_chat_client,
        run_chat_func=run_chat,
        run_agent_func=run_agent,
        get_resume_context_func=get_resume_context,
    )
if __name__ == "__main__":
    import sys

    raise SystemExit(main(sys.argv[1:]))
