from __future__ import annotations


def get_help_text() -> str:
    # Static help text shown by `/help` in the interactive prompt.
    return "\n".join(
        [
            "Commands:",
            "  @path[#Lx-Ly]  Attach a bounded file or exact text line range; press Tab for path completion.",
            "  /help   Show this help.",
            "  /model [model-name|default]  Show or switch the interactive session model.",
            "  /effort [auto|low|medium|high|xhigh|max]  Show or switch session reasoning effort.",
            "  /btw <question>  Ask one ephemeral, tool-free question using the current conversation.",
            "  /recap  Generate one concise, tool-free recap of the current conversation.",
            "  /config Show resolved provider and execution configuration.",
            "  /custom-commands  List personal and project prompt commands.",
            "  /plugin [list|details|install|enable|disable|uninstall|validate|config|marketplace]  Manage project-local plugins.",
            "  /mcp [list|get|add|add-json|remove]  Manage local, project, and user MCP servers.",
            "  /reload-plugins  Revalidate enabled plugins and refresh plugin-aware runtimes.",
            "  /agents [--max-agents N]  List personal, project, and plugin agent profiles.",
            "  /skills [--max-skills N]  List personal, project, and plugin skills.",
            "  /tools  Show the tools exposed to the model.",
            "  /tool <name>  Show one tool's description and input schema.",
            "  /tool-search [--max N] [--category CATEGORY] [--approval any|yes|no] <query>  Search tools.",
            "  /permissions  Show approval-gated tools and hard command blocks.",
            "  /checks [--max-checks N] Show suggested test, build, and lint commands.",
            "  /check-suggested-checks [max|--max-checks N] Preflight suggested test, build, and lint commands.",
            "  /run-suggested-checks [opts] [max|--max-checks N] Run suggested checks with optional output diagnostics.",
            "  /commands [--max-commands N] [--max-files N] Show project-defined commands from manifests.",
            "  /related-tests [--max-paths N] [--max-candidates N] -- [path...] Suggest test files related to paths or current git changes.",
            "  /focused-tests [--max-paths N] [--max-candidates N] [--max-commands N] -- [path...] Suggest focused test commands for paths or current git changes.",
            "  /check-focused-tests [--max-paths N] [--max-candidates N] [--max-commands N] -- [path...] Preflight focused test commands for paths or current git changes.",
            "  /run-focused-tests [opts] [--max-paths N] [--max-candidates N] [--max-commands N] -- [path...] Run focused test commands with optional output diagnostics.",
            "  /manifests [--max-files N] [--max-items N] Show package and pyproject manifest metadata.",
            "  /instructions [--max-files N] [--max-bytes N] Show AGENTS.md and CLAUDE.md instruction sources.",
            "  /hooks  Show resolved hook events, handlers, matchers, and sources.",
            "  /todos [--max-items N] [--max-files N] -- [path] Show TODO, FIXME, HACK, XXX, and BUG markers.",
            "  /command [--cwd PATH] -- <cmd> Preview whether a shell command can run.",
            "  /run [opts] -- <cmd> Run one finite shell command with optional output diagnostics.",
            "  ! <cmd> Run one bounded shell command and let the agent respond to its recorded output.",
            "  /check-run-commands [--cwd PATH] -- <cmd> ;; <cmd> Preview a short ordered command sequence.",
            "  /run-commands [opts] -- <cmd> ;; <cmd> Run a short ordered command sequence with optional output diagnostics.",
            "  /check-run-seq and /run-seq are aliases for the run-commands forms.",
            "  /check-start [--cwd PATH] -- <cmd> Preview starting one long-running shell command.",
            "  /start [--cwd PATH] -- <cmd> Start one long-running shell command in the current session.",
            "  /port <port> [host] [timeout-ms] [--host HOST] [--timeout-ms N] Check whether a local TCP port is reachable.",
            "  /http <url> [contains] [--timeout-ms N] [--max-body-chars N] [--contains TEXT] [--regex] Check HTTP status and optional response text.",
            "  /http-fetch <url> [--timeout-ms N] [--max-body-chars N] Fetch bounded HTTP response metadata and body text.",
            "  /overview [--max-files N] [--max-commands N] [--max-checks N] Show a compact project orientation bundle.",
            "  /repo-map [path] [--max-depth N] [--max-files N] [--max-symbols N] Show a bounded repository tree and source symbol map.",
            "  /search [--path PATH] [--max-matches N] [--regex] [--ignore-case] [--context-lines N] -- <query> Search project text with gitignore and safety filtering.",
            "  /search-contexts [--path PATH] [--max-matches N] [--regex] [--ignore-case] [--context-lines N] [--max-bytes N] -- <query> Search project text and show line-centered contexts.",
            "  /find-files [--path PATH] [--max-matches N] [--regex] [--case-sensitive] [--include-dirs] -- <query> Find project files by path fragment.",
            "  /glob [--max-matches N] [--include-dirs] -- <pattern> Find project files or directories by glob pattern.",
            "  /tree [path] [--max-depth N] [--max-entries N] Show a bounded project directory tree.",
            "  /symbols [--max-symbols N] -- <path...> Show source imports and symbol outlines.",
            "  /file-info <path...> Show file, directory, size, and line metadata.",
            "  /image-info <path...> Show image format, byte size, and dimensions.",
            "  /read [--max-bytes N] -- <path> [start[:end]] Read one project file or line range.",
            "  /around [--max-bytes N] -- <path> <line> [context-lines] Read one line with surrounding context.",
            "  /around-many [--max-bytes N] -- <path:line[:context-lines]...> Read several line-centered contexts.",
            "  /output-contexts [--context-lines N] [--max-contexts N] [--max-bytes N] -- <text> Extract file:line references from output and read contexts.",
            "  /output-diagnostics [--context-lines N] [--max-diagnostics N] [--max-contexts N] [--max-bytes N] -- <text> Summarize output errors/warnings and read referenced contexts.",
            "  /python-traceback [--context-lines N] [--max-diagnostics N] [--max-contexts N] [--max-bytes N] -- <text> Summarize Python traceback or pytest exception output.",
            "  /tail [--max-bytes N] -- <path> [lines] Read the last lines of one project file.",
            "  /read-files [--max-bytes N] [--line-numbers] -- <path...> Read multiple project files.",
            "  /read-ranges [--max-bytes N] -- <path:start[:end]...> Read multiple focused line ranges.",
            "  /python-check [path] Check Python syntax.",
            "  /python-deps [--max-files N] [--max-imports N] -- [path] Inspect Python imports and dependencies.",
            "  /python-defs [--path PATH] [--max-matches N] [--max-lines N] -- <symbol> [path] Find Python class/function definitions.",
            "  /python-refs [--path PATH] [--max-matches N] -- <symbol> [path] Find Python definitions, imports, and references.",
            "  /python-ref-contexts [--path PATH] [--max-matches N] [--context-lines N] [--max-bytes N] -- <symbol> [path] Find Python references with surrounding context.",
            "  /python-calls [--path PATH] [--max-matches N] -- <symbol> [path] Find Python call sites for a symbol.",
            "  /python-call-graph [--max-files N] [--max-edges N] -- [path] Inspect Python caller -> callee edges.",
            "  /python-rename-preview <symbol> <new_name> [path] Preview a Python symbol rename.",
            "  /python-rename <symbol> <new_name> [path] Rename a Python symbol.",
            "  /check-replace-python-def <symbol> <content> [path] Preview replacing one Python definition.",
            "  /replace-python-def <symbol> <content> [path] Replace one Python definition.",
            "  /config-check [path] Check JSON/YAML/TOML config syntax.",
            "  /check-json-set [--create-missing] <path> <pointer> <json-value> Preview a JSON value update.",
            "  /json-set [--create-missing] <path> <pointer> <json-value> Update one JSON value.",
            "  /check-json-remove <path> <pointer> Preview a JSON value removal.",
            "  /json-remove <path> <pointer> Remove one JSON value.",
            "  /check-json-patch <path> <json-ops-array> Preview JSON Patch operations.",
            "  /json-patch <path> <json-ops-array> Apply JSON Patch operations.",
            "  /check-replace-lines <path> <start> <end> <text> Preview a line-range replacement.",
            "  /replace-lines <path> <start> <end> <text> Replace a line range.",
            "  /check-insert-lines <path> <line> <text> Preview inserting text before a line.",
            "  /insert-lines <path> <line> <text> Insert text before a line.",
            "  /check-append <path> <text> Preview appending text to a file.",
            "  /append <path> <text> Append text to a file.",
            "  /check-write <path> <text> Preview writing one file.",
            "  /write <path> <text> Write one file.",
            "  /check-write-files <path> <text>... Preview writing multiple files.",
            "  /write-files <path> <text>... Write multiple files.",
            "  /check-edit <path> <old> <new> Preview replacing exact text in one file.",
            "  /edit <path> <old> <new> Replace exact text in one file.",
            "  /check-multi-edit <path> <old> <new>... Preview multiple exact replacements in one file.",
            "  /multi-edit <path> <old> <new>... Apply multiple exact replacements in one file.",
            "  /check-delete <path> Preview deleting one file.",
            "  /delete <path> Delete one file.",
            "  /check-delete-files <path...> Preview deleting multiple files.",
            "  /delete-files <path...> Delete multiple files.",
            "  /check-move <source> <destination> Preview moving one file.",
            "  /move <source> <destination> Move one file.",
            "  /check-move-files <source> <destination>... Preview moving multiple files.",
            "  /move-files <source> <destination>... Move multiple files.",
            "  /check-copy <source> <destination> Preview copying one file.",
            "  /copy <source> <destination> Copy one file.",
            "  /check-copy-files <source> <destination>... Preview copying multiple files.",
            "  /copy-files <source> <destination>... Copy multiple files.",
            "  /check-move-dir <source> <destination> Preview moving one directory.",
            "  /move-dir <source> <destination> Move one directory.",
            "  /check-move-dirs <source> <destination>... Preview moving multiple directories.",
            "  /move-dirs <source> <destination>... Move multiple directories.",
            "  /check-copy-dir <source> <destination> Preview copying one directory.",
            "  /copy-dir <source> <destination> Copy one directory.",
            "  /check-copy-dirs <source> <destination>... Preview copying multiple directories.",
            "  /copy-dirs <source> <destination>... Copy multiple directories.",
            "  /check-mkdir <path> Preview creating one directory.",
            "  /mkdir <path> Create one directory.",
            "  /check-mkdirs <path...> Preview creating multiple directories.",
            "  /mkdirs <path...> Create multiple directories.",
            "  /check-rmdir <path> Preview deleting one empty directory.",
            "  /rmdir <path> Delete one empty directory.",
            "  /check-rmdirs <path...> Preview deleting multiple empty directories.",
            "  /rmdirs <path...> Delete multiple empty directories.",
            "  /check-executable <path> [true|false] Preview setting a file executable bit.",
            "  /set-executable <path> [true|false] Set a file executable bit.",
            "  /check-patch <path> <patch|-> Preview applying a unified diff hunk to one file.",
            "  /patch <path> <patch|-> Apply a unified diff hunk to one file.",
            "  /check-patches <patch|-> Preview applying a unified diff across files.",
            "  /patches <patch|-> Apply a unified diff across files.",
            "  /check-regex-replace [opts] <path> <pattern> <replacement> Preview a regex replacement.",
            "  /regex-replace [opts] <path> <pattern> <replacement> Apply a regex replacement.",
            "  /code-deps [path] Inspect non-Python source imports and dependencies.",
            "  /code-refs [--path PATH] [--max-matches N] -- <symbol> [path] Find non-Python source references.",
            "  /code-ref-contexts [--path PATH] [--max-matches N] [--context-lines N] [--max-bytes N] -- <symbol> [path] Find non-Python source references with surrounding context.",
            "  /code-defs [--path PATH] [--max-matches N] [--max-lines N] -- <symbol> [path] Find non-Python source definitions.",
            "  /code-rename-preview <symbol> <new_name> [path] Preview a non-Python source rename.",
            "  /code-rename <symbol> <new_name> [path] Rename a non-Python source symbol or literal.",
            "  /git-status Show raw short git status.",
            "  /conflicts [path] Scan for unmerged git files and conflict marker lines.",
            "  /git-info Show git branch, HEAD, upstream, remotes, and short status.",
            "  /branches Show local git branches and current branch.",
            "  /log [path] [count] Show recent git commits, optionally scoped to a path.",
            "  /show [rev] [path] Show one git revision with stat and patch.",
            "  /blame <path> [start[:end]] Show git blame for a file or line range.",
            "  /stashes [count] Show local git stash entries.",
            "  /check-fetch [remote] Preview selecting a git remote to fetch.",
            "  /fetch [remote] Run git fetch --prune for a configured remote.",
            "  /check-pull Preview fast-forward pulling the current upstream.",
            "  /pull Fast-forward pull the current upstream.",
            "  /check-push Preview pushing the current branch to upstream.",
            "  /push Push the current branch to upstream.",
            "  /check-stash [--include-untracked] [message] Preview saving non-runtime changes to git stash.",
            "  /stash [--include-untracked] [message] Save non-runtime changes to git stash.",
            "  /check-stash-apply <stash@{N}> Preview applying a stash to a clean worktree.",
            "  /stash-apply <stash@{N}> Apply a stash to a clean worktree.",
            "  /check-stash-drop <stash@{N}> Preview deleting a stash entry.",
            "  /stash-drop <stash@{N}> Delete a stash entry.",
            "  /check-stage <path...> Preview staging explicit project paths.",
            "  /stage <path...> Stage explicit project paths in git.",
            "  /check-unstage <path...> Preview unstaging explicit project paths.",
            "  /unstage <path...> Unstage explicit project paths from git.",
            "  /check-commit <message> Preview committing currently staged changes.",
            "  /commit <message> Commit currently staged changes.",
            "  /check-restore <path...> Preview discarding unstaged tracked-file changes.",
            "  /restore <path...> Discard unstaged tracked-file changes.",
            "  /check-switch [--create] <branch> Preview switching or creating a local branch.",
            "  /switch [--create] <branch> Switch or create a local branch.",
            "  /env Show local OS, runtime, and tool availability.",
            "  /background-agents  List project-local background coding agents.",
            "  /background-agent-log <id> [max-chars]  Show bounded output from one background coding agent.",
            "  /stop-background-agent <id>  Stop one running background coding agent.",
            "  /send-background-agent <id> <message>  Queue a follow-up and respawn the agent if needed.",
            "  /respawn-background-agent <id>  Restart an agent from its recorded session.",
            "  /remove-background-agent <id>  Remove one non-running agent entry and logs while preserving its session.",
            "  /processes Show VibeAgent-started background processes.",
            "  /process <id> [chars] Show captured stdout and stderr for one background process.",
            "  /process-output-contexts <id> [chars] [--max-chars N] [--context-lines N] [--max-contexts N] [--max-bytes N] Extract file:line contexts from background command output.",
            "  /process-output-diagnostics <id> [chars] [--max-chars N] [--context-lines N] [--max-diagnostics N] [--max-contexts N] [--max-bytes N] Summarize diagnostics from background command output.",
            "  /wait-process <id> [timeout-ms] [chars] [--timeout-ms N] [--max-chars N] [--stdout TEXT] [--stderr TEXT] [--regex] Wait for one background process or output match.",
            "  /check-write-process <id> <text> [--stdin-file PATH] Preview writing stdin text or a project file to one running background process; quote text with spaces.",
            "  /write-process <id> <text> [--stdin-file PATH] Write stdin text or a project file to one running background process; quote text with spaces.",
            "  /check-stop-process <id> Preview stopping one VibeAgent-started background process.",
            "  /stop-process <id> Stop one VibeAgent-started background process.",
            "  /check-stop-processes, /check-stop-all-processes Preview stopping all VibeAgent-started background processes.",
            "  /stop-processes, /stop-all-processes Stop all VibeAgent-started background processes.",
            "  /status Show current mode, approval policy, resume context, and system-prompt state.",
            "  /context  Show the current project context sources for coding tasks.",
            "  /init [AGENTS.md|CLAUDE.md]  Create a starter project instruction file.",
            "  /doctor Show local configuration and workspace diagnostics.",
            "  /review [--max-files N] [--max-checks N] Review current git changes, syntax checks, suggested commands, and focused tests.",
            "  /code-review [low|medium|high|xhigh|max] [--fix] [target] Run verified multi-agent code review; edits only with --fix.",
            "  /simplify [target] Run verified reuse, simplicity, efficiency, and abstraction cleanup, then apply justified fixes.",
            "  /batch <instruction> Plan 5-30 independent units, ask for approval, then run worktree agents that open pull requests.",
            "  /security-review Review the current branch against origin/HEAD for verified security vulnerabilities.",
            "  /verify [goal] Build, run, and exercise the application with observable evidence.",
            "  /run-skill-generator [app] Validate and record a reusable project run recipe.",
            "  /handoff [--max-files N] [--max-checks N] [--max-status-chars N] [--max-plan-chars N] Show a final handoff bundle with review status, focused tests, and latest plan.",
            "  /changes [--max-files N] Show a structured changed-file summary.",
            "  /diff [--staged] [--max-chars N] [path]  Show the current git diff.",
            "  /diff-hunks [--staged] [--max-hunks N] [--max-lines N] [path]  Show structured git diff hunks.",
            "  /diff-contexts [--staged] [--context-lines N] [--max-hunks N] [--max-bytes N] [path]  Show source context around git diff hunks.",
            "  /clear  Clear chat history and loaded resume context.",
            "  /goal [condition|clear]  Set an autonomous completion goal, show status, or clear it.",
            "  /workflows [run <script.js>|show|resume|stop <id>]  Run and manage resumable multi-agent JavaScript workflows.",
            "  /list-agents  List reachable local peer sessions. Alias: /peers.",
            "  /peer-inbox [accept|deny <sender-id|all>]  Inspect or decide held peer messages.",
            "  /usage  Show local session usage from recorded events.",
            "  /cost   Show token usage and configured cost estimate.",
            "  /approval [next|default|acceptEdits|plan|auto|dontAsk|deny|bypassPermissions]  Show, cycle, or set the session permission mode.",
            "  /system-prompt [text|off]  Show, set, or clear the session system-prompt override.",
            "  /append-system-prompt [text|off]  Show, set, or clear extra session system-prompt instructions.",
            "  /add-dir [path|remove path|clear]  Show or update additional working directories for this session.",
            "  /cd <path>  Switch projects while preserving this conversation in a new session branch.",
            "  /sandbox  Show command sandbox configuration and Bubblewrap availability.",
            "  /sessions  List recent local sessions.",
            "  /rename [name]  Rename the active coding session; omit name to derive one from its first task.",
            "  /export [filename]  Print or write a safe plain-text transcript of the active coding session.",
            "  /session <run-id>  Show a compact session summary.",
            "  /last   Show a compact summary of the newest session.",
            "  /plan [run-id]  Show the latest recorded task plan.",
            "  /transcript [run-id] [--max-events N] [--max-text N]  Show a safe timeline of a session's events.",
            "  /session-search [--run run-id] [--max-matches N] [--case-sensitive] [--max-text N] <query>  Search a safe session timeline.",
            "  /session-commands [run-id] [--max-commands N] [--max-output-chars N]  Show bounded stdout/stderr from session commands.",
            "  /session-output-contexts [run-id] [--max-commands N] [--max-output-chars N] [--context-lines N] [--max-contexts N] [--max-bytes N]  Extract file:line contexts from session command output.",
            "  /session-output-diagnostics [run-id] [--max-commands N] [--max-output-chars N] [--context-lines N] [--max-diagnostics N] [--max-contexts N] [--max-bytes N]  Summarize diagnostics from session command output.",
            "  /session-files [run-id] [--max-files N]  Show project paths referenced by a session.",
            "  /session-failures [run-id] [--max-failures N] [--max-text N]  Show failed tools, commands, and approvals.",
            "  /session-verification [run-id] [--max-checks N]  Show verified, pending, and failed suggested checks.",
            "  /run-session-verification [run-id] [--max-checks N] [--timeout-ms N] [--max-output-chars N] [--no-failed] [--no-pending] [--continue-on-failure]  Rerun recorded failed and pending verification commands.",
            "  /session-audit [run-id] [--max-failures N] [--max-files N] [--max-commands N] [--max-checks N] [--max-text N]  Show finish-time readiness, blockers, active processes, checks, failures, commands, and files.",
            "  /session-handoff [run-id] [--max-failures N] [--max-files N] [--max-commands N] [--max-checks N] [--max-output-chars N] [--max-text N]  Show compact session recovery handoff bundle.",
            "  /checkpoint [label]  Save the current git status, diffs, and ordinary untracked files under .vibeagent.",
            "  /checkpoints  List saved local checkpoints.",
            "  /checkpoint-show <id|latest>  Show one saved local checkpoint.",
            "  /checkpoint-diff <id|latest>  Show saved staged and unstaged checkpoint patches.",
            "  /checkpoint-status <id|latest>  Compare current worktree state with a checkpoint.",
            "  /check-checkpoint-restore <id|latest>  Preview restoring tracked changes and saved untracked files from a checkpoint.",
            "  /checkpoint-restore <id|latest>  Restore tracked staged/unstaged changes and saved untracked files from a checkpoint.",
            "  /rewind [id|latest] [both|code|conversation]  List session rewind points or restore code, conversation, or both.",
            "  /undo [id|latest] [both|code|conversation]  Alias for /rewind.",
            "  /check-checkpoint-delete <id|latest>  Preview deleting one saved local checkpoint.",
            "  /checkpoint-delete <id|latest>  Delete one saved local checkpoint.",
            "  /check-checkpoint-prune <keep-last>  Preview pruning old checkpoints.",
            "  /checkpoint-prune <keep-last>  Prune old checkpoints while keeping the newest entries.",
            "  /resume [run-id|off] [--max-failures N] [--max-files N] [--max-commands N] [--max-checks N] [--max-output-chars N] [--max-text N]  Continue the same session from a previous session handoff and saved conversation, or clear it.",
            "  /compact [run-id] [--max-failures N] [--max-files N] [--max-commands N] [--max-checks N] [--max-output-chars N] [--max-text N]  Compact the newest or selected session handoff into resume context.",
            "  /bg [prompt]  Move the active coding session to a background agent; omit prompt to continue autonomously.",
            "  /branch [name]  Fork the current coding session into an independent branch.",
            "  /chat   Switch to daily conversation mode, or chat once with /chat <message>.",
            "  /code   Switch to coding mode, or run one coding task with /code <task>.",
            "  /exit   Exit the interactive prompt.",
            "",
            "In coding mode, normal input is treated as a programming task.",
            "In chat mode, normal input is treated as daily conversation.",
        ]
    )
