from __future__ import annotations

from .smart_code_formatting import (
    format_code_defs_report_text,
    format_code_deps_report_text,
    format_code_ref_contexts_report_text,
    format_code_refs_report_text,
)
from .smart_code_rename_commands import (
    format_code_rename_observation,
    format_code_rename_report_text,
    get_code_rename_preview_report,
    get_code_rename_preview_text,
    get_code_rename_report,
    get_code_rename_text,
)
from .smart_code_symbol_commands import (
    get_code_defs_report,
    get_code_defs_text,
    get_code_deps_report,
    get_code_deps_text,
    get_code_ref_contexts_report,
    get_code_ref_contexts_text,
    get_code_refs_report,
    get_code_refs_text,
)
from .smart_code_parsing import parse_rename_argument, parse_replace_python_definition_argument, parse_symbol_path_argument
from .smart_python_commands import (
    format_python_call_graph_report_text,
    format_python_calls_report_text,
    format_python_check_report_text,
    format_python_defs_report_text,
    format_python_deps_report_text,
    format_python_ref_contexts_report_text,
    format_python_refs_report_text,
    format_python_rename_observation,
    format_python_rename_report_text,
    format_replace_python_definition_observation,
    format_replace_python_definition_report_text,
    get_check_replace_python_definition_report,
    get_check_replace_python_definition_text,
    get_python_call_graph_report,
    get_python_call_graph_text,
    get_python_calls_report,
    get_python_calls_text,
    get_python_check_report,
    get_python_check_text,
    get_python_defs_report,
    get_python_defs_text,
    get_python_deps_report,
    get_python_deps_text,
    get_python_ref_contexts_report,
    get_python_ref_contexts_text,
    get_python_refs_report,
    get_python_refs_text,
    get_python_rename_preview_report,
    get_python_rename_preview_text,
    get_python_rename_report,
    get_python_rename_text,
    get_replace_python_definition_report,
    get_replace_python_definition_text,
)
