import unittest

from vibeagent.commands import get_help_text


HELP_SNIPPETS = [
    "/approval [ask|allow|auto|deny|dontAsk|plan]",
    "/custom-commands",
    "/agents [--max-agents N]",
    "/skills [--max-skills N]",
    "/config",
    "/resume [run-id|off] [--max-failures N] [--max-files N] [--max-commands N] [--max-checks N]",
    "previous session handoff",
    "/compact [run-id] [--max-failures N] [--max-files N] [--max-commands N] [--max-checks N]",
    "/branch [name]",
    "/plan [run-id]",
    "/transcript [run-id]",
    "/session-verification [run-id] [--max-checks N]",
    "/session-audit [run-id] [--max-failures N] [--max-files N] [--max-commands N] [--max-checks N]",
    "/checkpoint [label]",
    "/checkpoints",
    "/checkpoint-show <id|latest>",
    "/checkpoint-diff <id|latest>",
    "/checkpoint-status <id|latest>",
    "/check-checkpoint-restore <id|latest>",
    "/checkpoint-restore <id|latest>",
    "/check-checkpoint-delete <id|latest>",
    "/checkpoint-delete <id|latest>",
    "/check-checkpoint-prune <keep-last>",
    "/checkpoint-prune <keep-last>",
    "/status",
    "/context",
    "/init [AGENTS.md|CLAUDE.md]",
    "/doctor",
    "/review [--max-files N] [--max-checks N]",
    "/handoff [--max-files N] [--max-checks N] [--max-status-chars N] [--max-plan-chars N]",
    "/changes [--max-files N]",
    "/diff [--staged] [--max-chars N] [path]",
    "/diff-hunks [--staged] [--max-hunks N] [--max-lines N] [path]",
    "/diff-contexts [--staged] [--context-lines N] [--max-hunks N] [--max-bytes N] [path]",
    "/clear",
    "/usage",
    "/cost",
    "/system-prompt [text|off]",
    "/append-system-prompt [text|off]",
    "/add-dir [path|remove path|clear]",
    "/cd <path>",
    "/tools",
    "/tool <name>",
    "/permissions",
    "/checks [--max-checks N]",
    "/check-suggested-checks [max|--max-checks N]",
    "/run-suggested-checks [opts] [max|--max-checks N]",
    "/commands",
    "/related-tests [--max-paths N] [--max-candidates N] -- [path...]",
    "/focused-tests [--max-paths N] [--max-candidates N] [--max-commands N] -- [path...]",
    "/check-focused-tests [--max-paths N] [--max-candidates N] [--max-commands N] -- [path...]",
    "/run-focused-tests [opts] [--max-paths N] [--max-candidates N] [--max-commands N] -- [path...]",
    "/manifests",
    "/todos [--max-items N] [--max-files N]",
    "/command [--cwd PATH] -- <cmd>",
    "/run [opts] -- <cmd>",
    "/check-run-commands [--cwd PATH] -- <cmd> ;; <cmd>",
    "/run-commands [opts] -- <cmd> ;; <cmd>",
    "/check-run-seq and /run-seq are aliases",
    "/check-start [--cwd PATH] -- <cmd>",
    "/start [--cwd PATH] -- <cmd>",
    "/port <port> [host] [timeout-ms] [--host HOST]",
    "/http <url> [contains] [--timeout-ms N]",
    "/http-fetch <url> [--timeout-ms N]",
    "/verify [goal]",
    "/run-skill-generator [app]",
    "/overview [--max-files N]",
    "/repo-map [path] [--max-depth N]",
    "/search [--path PATH]",
    "/search-contexts [--path PATH]",
    "/glob [--max-matches N] [--include-dirs] -- <pattern>",
    "/tree [path] [--max-depth N]",
    "/symbols [--max-symbols N] -- <path...>",
    "/file-info <path...>",
    "/image-info <path...>",
    "/read [--max-bytes N] -- <path> [start[:end]]",
    "/read-files [--max-bytes N] [--line-numbers] -- <path...>",
    "/read-ranges [--max-bytes N] -- <path:start[:end]...>",
    "/around [--max-bytes N] -- <path> <line> [context-lines]",
    "/around-many [--max-bytes N] -- <path:line[:context-lines]...>",
    "/output-contexts [--context-lines N] [--max-contexts N] [--max-bytes N] -- <text>",
    "/output-diagnostics [--context-lines N] [--max-diagnostics N] [--max-contexts N] [--max-bytes N] -- <text>",
    "/python-traceback [--context-lines N] [--max-diagnostics N] [--max-contexts N] [--max-bytes N] -- <text>",
    "/tail [--max-bytes N] -- <path> [lines]",
    "/python-check [path]",
    "/python-deps [--max-files N] [--max-imports N] -- [path]",
    "/python-defs [--path PATH] [--max-matches N]",
    "/python-refs [--path PATH] [--max-matches N]",
    "/python-ref-contexts [--path PATH] [--max-matches N]",
    "/python-calls [--path PATH] [--max-matches N]",
    "/python-call-graph [--max-files N] [--max-edges N] -- [path]",
    "/python-rename-preview <symbol> <new_name> [path]",
    "/python-rename <symbol> <new_name> [path]",
    "/check-replace-python-def <symbol> <content> [path]",
    "/replace-python-def <symbol> <content> [path]",
    "/config-check [path]",
    "/check-json-set [--create-missing] <path> <pointer> <json-value>",
    "/json-set [--create-missing] <path> <pointer> <json-value>",
    "/check-json-remove <path> <pointer>",
    "/json-remove <path> <pointer>",
    "/check-json-patch <path> <json-ops-array>",
    "/json-patch <path> <json-ops-array>",
    "/check-replace-lines <path> <start> <end> <text>",
    "/replace-lines <path> <start> <end> <text>",
    "/check-insert-lines <path> <line> <text>",
    "/insert-lines <path> <line> <text>",
    "/check-append <path> <text>",
    "/append <path> <text>",
    "/check-write <path> <text>",
    "/write <path> <text>",
    "/check-write-files <path> <text>...",
    "/write-files <path> <text>...",
    "/check-edit <path> <old> <new>",
    "/edit <path> <old> <new>",
    "/check-multi-edit <path> <old> <new>...",
    "/multi-edit <path> <old> <new>...",
    "/check-delete <path>",
    "/delete <path>",
    "/check-delete-files <path...>",
    "/delete-files <path...>",
    "/check-move <source> <destination>",
    "/move <source> <destination>",
    "/check-move-files <source> <destination>...",
    "/move-files <source> <destination>...",
    "/check-copy <source> <destination>",
    "/copy <source> <destination>",
    "/check-copy-files <source> <destination>...",
    "/copy-files <source> <destination>...",
    "/check-move-dir <source> <destination>",
    "/move-dir <source> <destination>",
    "/check-move-dirs <source> <destination>...",
    "/move-dirs <source> <destination>...",
    "/check-copy-dir <source> <destination>",
    "/copy-dir <source> <destination>",
    "/check-copy-dirs <source> <destination>...",
    "/copy-dirs <source> <destination>...",
    "/check-mkdir <path>",
    "/mkdir <path>",
    "/check-mkdirs <path...>",
    "/mkdirs <path...>",
    "/check-rmdir <path>",
    "/rmdir <path>",
    "/check-rmdirs <path...>",
    "/rmdirs <path...>",
    "/check-executable <path> [true|false]",
    "/set-executable <path> [true|false]",
    "/check-patch <path> <patch|->",
    "/patch <path> <patch|->",
    "/check-patches <patch|->",
    "/patches <patch|->",
    "/check-regex-replace [opts] <path> <pattern> <replacement>",
    "/regex-replace [opts] <path> <pattern> <replacement>",
    "/code-deps [path]",
    "/code-refs [--path PATH] [--max-matches N]",
    "/code-ref-contexts [--path PATH] [--max-matches N]",
    "/code-defs [--path PATH] [--max-matches N]",
    "/git-status",
    "/git-info",
    "/branches",
    "/log [path] [count]",
    "/show [rev] [path]",
    "/blame <path> [start[:end]]",
    "/stashes [count]",
    "/check-fetch [remote]",
    "/fetch [remote]",
    "/check-pull",
    "/pull",
    "/check-push",
    "/push",
    "/check-stash [--include-untracked] [message]",
    "/stash [--include-untracked] [message]",
    "/check-stash-apply <stash@{N}>",
    "/stash-apply <stash@{N}>",
    "/check-stash-drop <stash@{N}>",
    "/stash-drop <stash@{N}>",
    "/check-stage <path...>",
    "/stage <path...>",
    "/check-unstage <path...>",
    "/unstage <path...>",
    "/check-commit <message>",
    "/commit <message>",
    "/check-restore <path...>",
    "/restore <path...>",
    "/check-switch [--create] <branch>",
    "/switch [--create] <branch>",
    "/env",
    "/processes",
    "/process <id> [chars]",
    "/wait-process <id> [timeout-ms] [chars] [--timeout-ms N]",
    "/check-write-process <id> <text> [--stdin-file PATH]",
    "/write-process <id> <text> [--stdin-file PATH]",
    "stdin text or a project file",
    "quote text with spaces",
    "/check-stop-process <id>",
    "/stop-process <id>",
    "/check-stop-processes",
    "/stop-processes",
    "/session-output-contexts [run-id]",
]


class HelpCommandTests(unittest.TestCase):
    def test_help_text_lists_local_commands(self) -> None:
        help_text = get_help_text()

        for snippet in HELP_SNIPPETS:
            with self.subTest(snippet=snippet):
                self.assertIn(snippet, help_text)


if __name__ == "__main__":
    unittest.main()
